/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Timer.h"

#include "SPI.h"
#include "rcc.h"
#include "NVIC.h"
#include "GPIO_interface.h"

extern SPI_Reg_t * SPI[4];
 uint32_t Auto_Load_Reg=36000;

int main(void)
{
	RCC_APB2_enableClock(12);
	RCC_APB1_EnableClock(14);
	RCC_APB1_EnableClock(2);

	NVIC_Pref_en(35);
	NVIC_Pref_en(36);
	NVIC_Pref_en(51);
	NVIC_Pref_en(84);
	RCC_APB2_enableClock(2);
	RCC_APB2_enableClock(3);

	RCC_APB2_enableClock(4);

	Pin_Config_t Led={
		.Port=PORTC,
		.Pin=PIN13,
		.Mode=Output_2MHZ,
		.output_mode=GP_output_PP
	};

	Pin_Config_t Channel1={
			.Port=PORTB,
			.Pin=PIN6,
			.Mode=Output_2MHZ,
			.output_mode=AF_output_PP
		};

	GPIO_INIT(&Channel1);


	Timer_Handle Timer4_H={
			.Timer_Num=Timer4,
			.Auto_Reload_Reg=36000,
			.Counting_Direction=upcounter,
			.comp_int=0,
			.pwm_mode=En_timer2_PWM_mode1,
			.sys_int=En_timer2_int,
			.prescaling=0,
	};
	Timer4_Init(&Timer4_H);




	Timer4_PWM_Mode_Init(Channel1_Timer,PWM_Mode1);


	Timer4_Start();
//	Timer4_Set_Channel_Duty_Cycle(Channel1_Timer,100);// 50->25k  100->122000

	GPIO_INIT(&Led);

	Pin_Config_t MOSI={
			.Port=PORTA,
			.Pin=PIN7,
			.Mode=Input,
//			.output_mode=AF_output_PP
			.input_mode=normal
		};

		GPIO_INIT(&MOSI);
	Pin_Config_t MISO={
				.Port=PORTA,
				.Pin=PIN6,
				.Mode=Output_2MHZ,
				.output_mode=AF_output_PP
			};

			GPIO_INIT(&MISO);
	Pin_Config_t SCLK={
					.Port=PORTA,
					.Pin=PIN5,
					.Mode=Output_2MHZ,
					.output_mode=AF_output_PP
				};

				GPIO_INIT(&SCLK);

	SPI_Handle_t SPI_Handle={

			.SPI_Number=SPI1,
			.SPI_En=En,
			.Duplex=Full_Duplex,
			.Master_Slave=Slave,
			.SS_En=Dis,
			.SW_Slave_Managament=1,
			.SSI=Dis,
			.SPI_TXEIE=Dis,
			.SPI_RXEIE=Dis

	};


	SPI_Init(&SPI_Handle);

	uint8_t y=0;
	uint8_t x=27;
	SPI_Recieve_Data_IT(&SPI_Handle,&y);






	/* Loop forever */
	for(;;);
}

